# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nicolas Aravena
tagline:          'Free lance and stuff'
description:      'Estudiante de Ingeniería Civil en Informática'
url:              http://nicoaravena.me

author:
  name:           'Nicolas Aravena'
  url:            https://twitter.com/Dalanth1

paginate:         5

# Custom vars
github:           http://github.com/dalanth