# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nicolas Aravena
tagline:          'Free lance and stuff'
description:      'Holo!'
url:              http://nicoaravena.me

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
github:           http://github.com/dalanth
  repo:           https://github.com/poole/hyde